 export const projects = [
  { project: "Website Redesign", type: "Web Development", date: "2025-08-01", name: "Alice Johnson", email: "alice.johnson@email.com" },
  { project: "Mobile App Launch", type: "Mobile Development", date: "2025-07-15", name: "Bob Smith", email: "bob.smith@email.com" },
  { project: "Brand Identity", type: "Design", date: "2025-06-28", name: "Cathy Lee", email: "cathy.lee@email.com" },
  { project: "Cloud Migration", type: "DevOps", date: "2025-05-10", name: "David Brown", email: "david.brown@email.com" },
  { project: "SEO Optimization", type: "Marketing", date: "2025-04-22", name: "Emma White", email: "emma.white@email.com" },
  { project: "E-commerce Setup", type: "Web Development", date: "2025-03-30", name: "Frank Green", email: "frank.green@email.com" },
  { project: "Logo Design", type: "Design", date: "2025-03-15", name: "Grace Kim", email: "grace.kim@email.com" },
  { project: "Server Upgrade", type: "DevOps", date: "2025-02-28", name: "Henry Ford", email: "henry.ford@email.com" },
  { project: "Social Media Campaign", type: "Marketing", date: "2025-02-10", name: "Ivy Brown", email: "ivy.brown@email.com" },
  { project: "Mobile Game", type: "Mobile Development", date: "2025-01-25", name: "Jack Black", email: "jack.black@email.com" },
  { project: "API Integration", type: "Web Development", date: "2025-01-05", name: "Karen Lee", email: "karen.lee@email.com" },
  { project: "UI Refresh", type: "Design", date: "2024-12-18", name: "Larry Page", email: "larry.page@email.com" },
  { project: "Backup Solutions", type: "DevOps", date: "2024-12-02", name: "Mona Lisa", email: "mona.lisa@email.com" },
  { project: "Content Strategy", type: "Marketing", date: "2024-11-17", name: "Ned Stark", email: "ned.stark@email.com" },
  { project: "Mobile Payments", type: "Mobile Development", date: "2024-11-01", name: "Olivia Rose", email: "olivia.rose@email.com" },
  { project: "Performance Audit", type: "Web Development", date: "2024-10-15", name: "Paul Walker", email: "paul.walker@email.com" },
  { project: "Brand Guidelines", type: "Design", date: "2024-10-01", name: "Quinn Davis", email: "quinn.davis@email.com" },
  { project: "Infrastructure Automation", type: "DevOps", date: "2024-09-14", name: "Rachel Ray", email: "rachel.ray@email.com" },
  { project: "Email Marketing", type: "Marketing", date: "2024-09-01", name: "Sam Smith", email: "sam.smith@email.com" },
  { project: "Fitness Tracker App", type: "Mobile Development", date: "2024-08-18", name: "Tina Fey", email: "tina.fey@email.com" },
];
